# Generated by Django 4.0.5 on 2022-06-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Image order')),
                ('image', models.ImageField(help_text="Don't forget to specify the order of the picture", upload_to='places', verbose_name='The place image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'verbose_name': 'Place image',
                'verbose_name_plural': 'Place images',
            },
        ),
    ]
