# Generated by Django 4.0.5 on 2022-06-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order'], 'verbose_name': 'Place image', 'verbose_name_plural': 'Place images'},
        ),
    ]
